version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:8787
    depends_on:
      - api

  api:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./apps/api:/app
      - /app/node_modules
    ports:
      - "8787:8787"
    command: npm run dev
    environment:
      - NODE_ENV=development
